//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generations_Launcher_Front.TextStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generations_Launcher_Front.TextStore.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antialiasing (FXAA).
        /// </summary>
        public static string AA_label {
            get {
                return ResourceManager.GetString("AA_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Adapter.
        /// </summary>
        public static string Adapter_label {
            get {
                return ResourceManager.GetString("Adapter_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Configuration.
        /// </summary>
        public static string AdvancedConfiguration {
            get {
                return ResourceManager.GetString("AdvancedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Level Caching Options.
        /// </summary>
        public static string AdvancedLevelCachingOptions {
            get {
                return ResourceManager.GetString("AdvancedLevelCachingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is supported by IncludeApp.
        ///
        ///IncludeApp is a game monitoring system that provides developers with detailed information regarding how their games are played.
        ///
        ///If you agree to activate this feature, your game will upload data that can be used to analyse your game-play experience -- data that helps developers tailor their products to current gaming trends.
        ///
        ///We assure you no personal information can be accessed by IncludeApp and that there is no security risk by agreeing to let this product upload  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analytics_Label {
            get {
                return ResourceManager.GetString("Analytics_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics Enabled?.
        /// </summary>
        public static string AnalyticsGlobalCheck {
            get {
                return ResourceManager.GetString("AnalyticsGlobalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letterbox.
        /// </summary>
        public static string Aspect_Combo {
            get {
                return ResourceManager.GetString("Aspect_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Configuration.
        /// </summary>
        public static string AudioConfiguration {
            get {
                return ResourceManager.GetString("AudioConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Device.
        /// </summary>
        public static string AudioDevice_label {
            get {
                return ResourceManager.GetString("AudioDevice_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Block Size.
        /// </summary>
        public static string CacheBlockSize {
            get {
                return ResourceManager.GetString("CacheBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Size.
        /// </summary>
        public static string CacheSize {
            get {
                return ResourceManager.GetString("CacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error!.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default_combo {
            get {
                return ResourceManager.GetString("Default_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset to defaults.  No DefaultInput.cfg file found.
        ///Reinstall to restore the DefaultInput.cfg file..
        /// </summary>
        public static string DefaultInputMissing {
            get {
                return ResourceManager.GetString("DefaultInputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string DisplayMode_Label {
            get {
                return ResourceManager.GetString("DisplayMode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialise DirectX components.
        ///This application will now close.
        /// </summary>
        public static string DXFailed {
            get {
                return ResourceManager.GetString("DXFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Advanced Level Caching.
        /// </summary>
        public static string EnableAdvancedLevelCaching {
            get {
                return ResourceManager.GetString("EnableAdvancedLevelCaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Configuration.
        /// </summary>
        public static string Graphics_Label {
            get {
                return ResourceManager.GetString("Graphics_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Configuration .
        /// </summary>
        public static string GraphicsConfiguration {
            get {
                return ResourceManager.GetString("GraphicsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High_Combo {
            get {
                return ResourceManager.GetString("High_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Configuration.
        /// </summary>
        public static string InputConfiguration {
            get {
                return ResourceManager.GetString("InputConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Type.
        /// </summary>
        public static string InputTypeLabel {
            get {
                return ResourceManager.GetString("InputTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Keyboard_Back {
            get {
                return ResourceManager.GetString("Keyboard_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Keyboard_Down {
            get {
                return ResourceManager.GetString("Keyboard_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Keyboard_Left {
            get {
                return ResourceManager.GetString("Keyboard_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard_Name {
            get {
                return ResourceManager.GetString("Keyboard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Keyboard_Return {
            get {
                return ResourceManager.GetString("Keyboard_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Keyboard_Right {
            get {
                return ResourceManager.GetString("Keyboard_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string Keyboard_Tab {
            get {
                return ResourceManager.GetString("Keyboard_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Keyboard_Up {
            get {
                return ResourceManager.GetString("Keyboard_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low_Combo {
            get {
                return ResourceManager.GetString("Low_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic Generations - Configuration.
        /// </summary>
        public static string Main_App_Title {
            get {
                return ResourceManager.GetString("Main_App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium_Combo {
            get {
                return ResourceManager.GetString("Medium_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None_Combo {
            get {
                return ResourceManager.GetString("None_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Compatible Graphics Adapter Found.
        /// </summary>
        public static string NoValidAdapter_Label {
            get {
                return ResourceManager.GetString("NoValidAdapter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off_combo {
            get {
                return ResourceManager.GetString("Off_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On_combo {
            get {
                return ResourceManager.GetString("On_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover the cursor over a button slot and press the desired key on the keyboard or controller to reassign button allocation..
        /// </summary>
        public static string Pad_Instructions {
            get {
                return ResourceManager.GetString("Pad_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection Quality.
        /// </summary>
        public static string Reflection_Check {
            get {
                return ResourceManager.GetString("Reflection_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Res_label {
            get {
                return ResourceManager.GetString("Res_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string ResetDefaultButton {
            get {
                return ResourceManager.GetString("ResetDefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Quit.
        /// </summary>
        public static string SaveQuit_Button {
            get {
                return ResourceManager.GetString("SaveQuit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Quality.
        /// </summary>
        public static string Shadow_Check {
            get {
                return ResourceManager.GetString("Shadow_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Configuration.
        /// </summary>
        public static string StatsConfiguration {
            get {
                return ResourceManager.GetString("StatsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Rate.
        /// </summary>
        public static string StreamingRate {
            get {
                return ResourceManager.GetString("StreamingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any controller&apos;s Start button during play to switch to that controller..
        /// </summary>
        public static string SwitchPadInstruction_label {
            get {
                return ResourceManager.GetString("SwitchPadInstruction_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Sync.
        /// </summary>
        public static string VSync_Check {
            get {
                return ResourceManager.GetString("VSync_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widescreen.
        /// </summary>
        public static string Widescreen_Combo {
            get {
                return ResourceManager.GetString("Widescreen_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in Windowed Mode.
        /// </summary>
        public static string Windowed_Check {
            get {
                return ResourceManager.GetString("Windowed_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox 360 Controller for Windows.
        /// </summary>
        public static string Xbox_Pad_Name {
            get {
                return ResourceManager.GetString("Xbox_Pad_Name", resourceCulture);
            }
        }
    }
}
